trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: SSH@0
  inputs:
    sshEndpoint: 'ssh-ivm-dev'
    commands: |
      cd /home/ivm-admin/frappe-bench/apps/ivm && git pull origin develop && cd /home/ivm-admin/frappe-bench && bench build && bench migrate && bench restart
    failOnStderr: false
  displayName: 'Deploy'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))