"""Auto-export customizations when they change in the UI"""
import json
import os
import frappe
from frappe import scrub
from frappe.modules.utils import export_customizations
from ivm.utils.cleanup_custom_fields import cleanup_deleted_fields


def auto_export_custom_field(doc, method):
    """Auto-export Custom Field changes to custom/doctype.json"""
    # Skip if we're in install, migrate, sync, or import mode
    if (
        frappe.flags.in_install
        or frappe.flags.in_migrate
        or frappe.flags.in_import
        or frappe.flags.in_sync_customizations
    ):
        return

    # Skip if developer mode is not enabled
    if not frappe.conf.developer_mode:
        return

    # Get the doctype being customized
    doctype = doc.dt

    # Track deleted fields per doctype (for handling multiple deletions in one request)
    if method == "on_trash":
        if not hasattr(frappe.local, "deleted_custom_fields"):
            frappe.local.deleted_custom_fields = {}
        if doctype not in frappe.local.deleted_custom_fields:
            frappe.local.deleted_custom_fields[doctype] = set()
        frappe.local.deleted_custom_fields[doctype].add(doc.name)
    
    # For deletions, defer the export to after_commit so the database is updated
    if method == "on_trash":
        frappe.db.after_commit.add(lambda: _do_export_and_cleanup(doctype))
        return

    # For inserts and updates, export immediately  
    _do_export_and_cleanup(doctype)


def _do_export_and_cleanup(doctype):
    """Perform the actual export and cleanup operations"""
    # Debounce: Only export once per request per doctype
    if not hasattr(frappe.local, "auto_exported_doctypes"):
        frappe.local.auto_exported_doctypes = set()

    if doctype in frappe.local.auto_exported_doctypes:
        return

    frappe.local.auto_exported_doctypes.add(doctype)

    try:
        # Export customizations for this doctype
        export_customizations(
            module="IVM",
            doctype=doctype,
            sync_on_migrate=True,
            with_permissions=False
        )

        # Get all fields being deleted in this request (if any)
        deleted_fields = None
        if hasattr(frappe.local, "deleted_custom_fields") and doctype in frappe.local.deleted_custom_fields:
            deleted_fields = list(frappe.local.deleted_custom_fields[doctype])
        
        cleanup_deleted_fields(doctype, silent=True, exclude_fields=deleted_fields)

        # Add warning header to the exported file
        _add_warning_header(doctype)

        # Show a subtle toast notification instead of a dialog
        frappe.publish_realtime(
            "show_alert",
            {"message": f"Auto-exported customizations for {doctype}", "indicator": "green"},
            user=frappe.session.user
        )
    except Exception as e:
        frappe.log_error(f"Auto-export failed for {doctype}: {str(e)}", "Auto Export Error")


def auto_export_property_setter(doc, method):
    """Auto-export Property Setter changes to custom/doctype.json"""
    # Skip if we're in install, migrate, sync, or import mode
    if (
        frappe.flags.in_install
        or frappe.flags.in_migrate
        or frappe.flags.in_import
        or frappe.flags.in_sync_customizations
    ):
        return

    # Skip if developer mode is not enabled
    if not frappe.conf.developer_mode:
        return

    # Get the doctype being customized
    doctype = doc.doc_type
    
    # For deletions, defer to after_commit so the database is updated
    if method == "on_trash":
        frappe.db.after_commit.add(lambda: _do_export_and_cleanup(doctype))
        return

    # For inserts and updates, export immediately
    _do_export_and_cleanup(doctype)


def _add_warning_header(doctype):
    """Add warning header to the exported custom JSON file"""
    try:
        # Get the path to the custom file
        module_name = "ivm"
        file_path = frappe.get_app_path("ivm", module_name, "custom", f"{scrub(doctype)}.json")
        
        if not os.path.exists(file_path):
            return
        
        # Read the existing JSON
        with open(file_path, "r") as f:
            data = json.load(f)
        
        # Add warning field at the beginning (if not already present)
        if "_WARNING" not in data:
            warning_data = {
                "_WARNING": "Do not edit this file manually. See README.md in this directory for instructions."
            }
            
            # Merge warning at the beginning
            new_data = {**warning_data, **data}
            
            # Write back with warning
            with open(file_path, "w") as f:
                json.dump(new_data, f, indent=1, sort_keys=False)
        else:
            # Warning already exists, no need to update
            pass
                
    except Exception as e:
        frappe.log_error(f"Failed to add warning header: {str(e)}", "Warning Header Error")
